// Public surface of the diagnosis engine. The extension and tests import from here.
export { RuleCatalog } from './rule-catalog';
export { ConsoleDiagnoser } from './console-diagnoser';
export type { EnrichOptions } from './console-diagnoser';
export type { Enricher, EnrichmentContext, DiagnosisEngine } from './enricher';
export { ClassFacts } from './enricher';
export { ActuatorEnricher } from './actuator-enricher';
export { PropertyPrecedenceEnricher } from './property-precedence-enricher';
export { PsiEnricher } from './psi-enricher';
export { overallHealth, firstDownComponent, effectivePropertySource } from './actuator-reader';
export { LlmDiagnosisEngine } from './llm-diagnosis-engine';
export { OllamaHttpClient } from './ollama-http-client';
export type { OllamaClient } from './ollama-http-client';
export { RuleBasedClassifier } from './rule-based-classifier';
export { BuildOutputAnalyzer, isSpringRelated } from './build-output-analyzer';
export { extract } from './log-extractor';
export { segment } from './stack-trace-segmenter';
export { failureTexts, hasFailures } from './test-results-parser';
export { locate } from './test-results-locator';
export { isRunStart, containsRunStart, lastRunSlice } from './log-run-boundary';
export { containsErrorSignature } from './error-signature';
export { fromProperties, fromYaml, discoverAll, resolveAgainstModule } from './log-file-property-finder';
export { groupingKey } from './models';
export type { DiagnosisCard, Phase, Confidence } from './models';
export { RawSignal } from './models';
export type { Rule, SignalCriteria } from './rule';
